services:
  api:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ping || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3